# Generated by Django 5.0.6 on 2025-02-21 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dept_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='description',
            new_name='dept_description',
        ),
    ]
